// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxHcMlziG_PIIIxQ0b8A3SiJIb_HIM5vU',
    appId: '1:395999364947:android:39ef58eb70e27b6a5583a6',
    messagingSenderId: '395999364947',
    projectId: 'thokbazaar-4a79a',
    storageBucket: 'thokbazaar-4a79a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUP8kOGzrACTG5pMLTHhx4dxEEhIrcSlg',
    appId: '1:395999364947:ios:48e659f9e2a466255583a6',
    messagingSenderId: '395999364947',
    projectId: 'thokbazaar-4a79a',
    storageBucket: 'thokbazaar-4a79a.firebasestorage.app',
    iosBundleId: 'com.thokbazaar.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPBF_TufuqTp4lTCJJeYPGtJs54cDKP30',
    appId: '1:395999364947:web:1177c9d7eb686f3a5583a6',
    messagingSenderId: '395999364947',
    projectId: 'thokbazaar-4a79a',
    authDomain: 'thokbazaar-4a79a.firebaseapp.com',
    storageBucket: 'thokbazaar-4a79a.firebasestorage.app',
  );
}
